name: "dataUpdate"

on:
  schedule:
    - cron: '00 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: update
    steps:
    - uses: actions/checkout@v2
    - name: Update Data
      run: sh ./script/update.sh
    - name: setting git
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name "アカウント名"
        git add .
        git commit -m "update current_data $(date '+%Y%m%d')"
        git push origin master
